### ISSUE TITLE
Canonicalization requirements for directories

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#104]
To avoid issues with signing, directories should (perhaps) return "canonicalized" TDs.   See https://github.com/w3c/wot-profile/issues/55 and the linked issues in security and thing-description.

Note: this is an implementation requirement for directories.   
Alternative: the "signer" could canonicalize internally, and this might be better (less fragile).

**Comment by mmccool** [comment]
Some further thoughts on this:
1. Directories can avoid breaking signing by always storing the string value returned by the endpoint and returning it when requested.  
2. For unencrypted TDs, the TD could still be parsed and stored as a data structure for the purposes of queries and returning fragments.
3. For encrypted TDs, basically the consumer would have to know the ID of the TD in advance.  However, if it is encrypted, the id cannot be extracted from the TD itself.  Perhaps an ID should be included in the registration API (may or may not be the same as the internal ID or the local directory ID) and this can be stored in side-band information available to the query engine.
4. For fragments, perhaps we want to include the option of signing them with chained proofs.

The above assumes that "additional" metadata is associated with a TD without modifying the TD itself, which relates to issue https://github.com/w3c/wot-discovery/issues/98

**Comment by AndreaCimminoArriaga** [comment]
The issue about the frame is the following https://github.com/w3c/wot-thing-description/issues/1015

**Comment by farshidtz** [comment]
I do agree that this may be necessary to guaranty stability of numbers beyond double-precision floating-point, if TDs indeed include any. Nevertheless, I think adding constraints on how the TD should be handled internally reduces the possibilities of server optimization (e.g. either servers need to store and work with string or binary blobs or need to always store a copy). Ideally, we should rely on signature verification algorithms that are agnostic to JSON string encoding (spacing, sorting).

If required, the original string or binary blob can be requested through content type negotiation. E.g. for binary, the client can set Accept header to `application/octet-stream`.

**Comment by AndreaCimminoArriaga** [comment]
I agree with @farshidtz regarding constraining TDs internally, not only from the optimisations point of view, but also others like validation or how to store such TDs (recall that TDs are RDF and there are a wide range of technologies/proposals for different scopes that could be potentially used).

**Comment by mmccool** [comment]
The trouble is that bit-perfect canonicalization is currently an unsolved problem for JSON-LD.   Storing the original string is the easiest way around this that is guaranteed to work.  Yes, it adds a constraint on the implementation, but not a huge one, IMO.   Retrieving the string can be handled as a special case in the RESTful API; no need to put it into an RDF store, etc.

**Comment by mmccool** [comment]
Note that this is somewhat orthogonal to the problem of using canonicalization during signing.  We still *should* define a canonicalization method to use during signing to make it more reliable, and there are cases where a directory might have to sign a modified TD itself (eg if it embeds new information in it), in which case it should be canonicalized before signing (and framed as a TD...).

I also agree that canonicalization of TDs specifically may be an easier problem than canonicalizing JSON-LD.  Maybe.

**Comment by AndreaCimminoArriaga** [comment]
I think that the canonicalisation issue is not due to the JSON-LD, but to the frame used in the TDs. Currently, the TD assumes that all the subjects in a TD are blank nodes and that only the subject that has the td:Thing type is an IRI (either explicitly or implicitly). Under that assumption the JSON-LD 1.0 serialisations expanded, compacted, or flattened should provide the same JSON-LD structure. Furthermore, any other RDF serialisation will not have this kind of conflict.

Storing the original TD for signing or returning such TD when requested, and then store the same TD in another serialisation for performing SPARQL search or SHACL validation, ends up in a kind of architecture that will not scale since it must rely on two different data storage systems that will contain twice the same data.

Under this point of view, for me the key issue is using one of the JSON-LD 1.1 serialisations without the framing and clearly state the assumptions over the subjects (or maybe use any other RDF serialisation under the hood). But the problem with this is that there is no way to give back a framed TD, which can be odd if a user register a TD framed but a directory can not give back such TD with the same structure.

**Comment by mmccool** [comment]
Storing and signing a string doesn't really deal with signing of chained results (eg with annotations) very well.  So the string thing is a hack, but can be our plan B if we don't come up with a formal canonicalization.  BTW, the string does NOT have to be stored in RDF, etc.  My idea is that an implementation can store this completely separately from the main database and we can define a special sub-API to retrieve it.  An implementation can special-case that sub-API and use a very simple name-value DB to store the string.

**Comment by AndreaCimminoArriaga** [comment]
For the specific problem of signing the string I agree that this is not an issue, but for storing and handling the TDs it can become a problem. 
The lack of a frame to translate a JSON-LD 1.1  document (or any RDF serialisation) to the current format of the TDs hinders storing the TDs in a triple store, and therefore, it prevents using any W3C standard technology for RDF like shapes (for validation), reasoning (using owl), ... . The problem is not that TDs are framed since they are still RDF and therefore their serialisation can be changed, the problem raises when we need to re-write the RDF documents into the specific frame of WoT TDs.
As a note, we need to move TDs from JSON-LD 1.1 framed into another serialisation because triple stores do not support JSON-LD 1.1 documents, even less those framed. 

As a conclusion, "we can live" with this issue but it forces implementation to adopt "bad" decisions like having data (TDs) stored duplicated (one in JSON-LD 1.1 framed, and other in a different RDF serialisation). I think the solution is proving the frame to do the round trip translation among serialisations.

**Comment by mmccool** [comment]
We have generally decided to defer canonicalization and signing of TDs to a future spec, intersecting with RDF-signatures, etc.  So propose closing this.  When we look at the requirements for signing in the future we may, or may not, need to add canonicialization, but we can deal with it then.

**Comment by mmccool** [comment]
Also marked as "Discuss", just in case.
