### ISSUE TITLE
Allow plain HTTP in some cases

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#139]
Need to clarify when it's ok to use "plain" HTTP, i.e. on a secure local network.
Unfortunately due to lack of support for "local HTTPS" this is necessary, although not ideal.

Note: We may want to consider some way to bootstrap allocating a local certificate as well, but if the purpose is to support dashboards in a browser and the browser does not allow self-signed certs it won't work...

**Comment by benfrancis** [comment]
As discussed in the vF2F call today, WebThings Gateway serves its API on both a global foo.webthings.io subdomain using HTTPS and the gateway.local domain using plain HTTP. Because TLS can't really be used with a .local domain, the constraint that directories must use HTTPS would mean the local directory could not be compliant with the spec.

I don't think allowing a local/self-signed certificate will work, at least for web browsers where this requires manually adding a trusted root certificate in the browser settings or manually bypassing security warnings.

I suggest the spec should recommend the use of TLS, but not require it, at least not on local networks.

**Comment by benfrancis** [comment]
Further to this, it wasn't clear to me from the specification whether it's possible to have public directories (i.e. with no authentication required).

I can imagine cases where you would want a directory which is public, or at least read-only without authentication. E.g. for a smart city.

It would be great if this could be made more explicit too.

**Comment by mmccool** [comment]
Ben, would you be willing to create a PR that suggests some contexts in which plain HTTP is acceptable?   Be aware that we will almost certainly be questioned about this, and it may even trigger formal objections, so if we can find *any* mechanism that supports TLS it would be better.  In particular, a "public service" (e.g. for a smart city) can use TLS without requiring authentication.  This is still public but protects queries and returned data against prying eyes.  Therefor I think for public services you want to use HTTPS and this is not a justification for HTTP.  So I think the only possible exception is local HTTP on a private network that has its own security.  Even then, if it is possible to manually accept a certificate, or install one manually, that option should be used.  We may also want to limit the functionality of directory services available over HTTP, i.e. make them read-only, etc.  In particular I think device-to-device implementations (i.e. hubs talking to local devices) should use HTTPS and negotiate local certs (i.e. during an onboarding process, which we can leave unspecified, but can say it should result in the self-signed certificate of the device being registered with the hub, and probably vice-versa).   If the hub is providing a local HTTP dashboard UI rather than the directory API directly that might be a reasonable approach, too.

I'm still *highly* annoyed that some form of local HTTPS is *still* not supported by browsers.   It's the whole "browsers flagging self-signed certs as evil and scaring users" rather than letting the user simply install them when they know what they are doing that is the problem...

**Comment by benfrancis** [comment]
Yes I could draft a PR.

For the record, the specific use case I have in mind is WebThings Gateway which already provides a [directory API](https://webthings.io/api/#things-resource) and a web interface to represent the collection of things in that directory in a user interface:

![WebThings Gateway things view](https://webthings.io/gateway/images/things_ui_screenshot.png)

Both the API and web interface are served from the same `/things` URL (returning either JSON or HTML based on HTTP content negotiation) which is served at both https://example.webthings.io/things for remote access and http://gateway.local/things for local access.

In this case, self-signed certificates are not an option because of the UX issues in web browsers and read-only is not an option either because the full functionality of the gateway is provided via the .local gateway domain so that you can still use your smart home if your internet connection goes down! At one point we did prototype building WebThings Gateway into home routers to have more control over DNS config in order to resolve remote domains locally, but it doesn't work very well in practice (browsers often have their own DNS configuration rather than rely on one provided via DHCP) and we've since discontinued that experiment.

As far as hubs talking to things using self-signed certificates, we may have more control over that because it's the gateway that's acting as the HTTP client. Ultimately there has to be a trusted certificate authority to act as the root of trust, which in that case could be the hub itself. I'd be interested to see a working prototype of that if anyone wants to try, but that doesn't help with the Directory Service API.

The question about whether it's possible to have public directories with no authentication is really a separate question, and I agree they would probably want to use HTTPS (and likely be read-only in most cases).

**Comment by mmccool** [comment]
This has been generally cleaned up at this point with the addition of assertions on use of TLS in the Architecture document, which we now refer to.  Propose closing.
