### ISSUE TITLE
Implementing a DNS-based approach, are DNS-SD and mDNS mandatory? 

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-discovery#200]
From section 5.3.
>A Thing or Thing Description Directory may use the DNS-Based Service Discovery (DNS-SD)[RFC6763]. This can be also be used to discover them on the same link by combining Multicast DNS (mDNS)[RFC6762]. 

As reader it is not clear if DNS-SD and mDNS are required here or not, since both are MAY. Continue reading and seeing the example in Figure 2 and 3 it seems that both are kind of required. It would be great to be more specific here.

**Comment by sebastiankb** [comment]
Another feedback:
Figure 2 and 3 uses for the parameter `td` relative paths such as` /.well-known/wot-thing-description`. However, the `td` parameter is defined by 

>td
    Absolute pathname of the Thing Description of the Thing or Directory Description of the Thing Description Directory.

What is correct?

**Comment by k-toumura** [comment]
Not every Thing or Thing Description Directory need to implement DNS-based service discovery.  So we use "may" here.   If you want your Thing to be DNS-SD discoverable, the service name you use should be `_wot`.  The sequences are examples of how DNS-SD and mDNS can be combined.

And, `/.well-known/wot-thing-description` is not a relative path because it starts with a `/`(slash).  Host part of URL can be create from SRV record of DNS response.

**Comment by sebastiankb** [comment]
@k-toumura thanks for the information. I am not a DNS expert. I just want to be sure that the text is clear enough for developers to implement.

**Comment by mmccool** [comment]
No introduction mechanism is meant to be mandatory.   Any means by which the URL of a Thing or a TDD can be obtained is acceptable; introductions are all just on-ramps leading to the same highway.  So the action here is to revise the text so that is clear.

**Comment by mmccool** [comment]
In fact no introduction mechanism is mandatory, so the action to resolve this is to say that clearly somewhere.

**Comment by mmccool** [comment]
Suggest the following (informative) sentence should be added to the intro:

"No particular introductory mechanism is mandatory, as long as a URL of an exploration service is somehow obtained."

**Comment by mmccool** [comment]
See https://github.com/w3c/wot-discovery/pull/221
I made some other changes as well, because the existing intro seems to say that TDs can be returned by an introduction.  They cannot, the result should *always* be a TD.  We might have to revise some text elsewhere to fully clean this up.  I also wanted to make clear that multiple intro mechanisms can be used and the results merged (this could be clearer, perhaps adding more text to the intro to explorations, since multiple intro results mean multiple exploration service contents, and "merging the results" means the end result is a SET of TDs)
