### ISSUE TITLE
Small text improvements for 6.2.2.1.5 Listing

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-discovery#203]
Maybe I'm being too picky, but I find this statement kind of confusing:

>The listing endpoint provides a way to query the collection of TD objects from the directory. The Search API may be used to retrieve TD fragments; see § 6.2.2.4 Search. 

It sounds that a kind of filter can be applied here for listing. Better would be:

"The listing endpoint provides a way to retrieve all TDs that are stored in the directory. If a filter-based result is needed, apply the search API; see § 6.2.2.4 Search."

Another text which is maybe not very clear:

[Example 7](https://w3c.github.io/wot-discovery/#example-pagination) says it query 12 TDs. It sounds that the client can provide the number of TDs that are returned. However, the situation here is that the TD repository has only 12 TDs stored that are returned by pagination, right?

**Comment by farshidtz** [comment]
Moreover, it looks like the examples have the old path: `/td` instead of `/things`

**Comment by farshidtz** [comment]
> It sounds that a kind of filter can be applied here for listing.

It was intentional. The search API can be used for pagination. E.g. JSONPath `$[0:10]` to get the the first 10 items.

**Comment by sebastiankb** [comment]
>It was intentional. The search API can be used for pagination. E.g. JSONPath $[0:10] to get the the first 10 items.

Now I'm more confused. Listing (as also defined in the [TD](https://w3c.github.io/wot-discovery/#directory-api-spec)) says that it retrieve all Thing Descriptions. Based on the TD I have to call `/things` or `/things{?offset,limit,sort_by,sort_order}`  for that. No filtering is possible here, right?

When I like to apply a filter then I have to use the search API like `/search/jsonpath?query={query}` . How I can use pagination here? I think more examples in the specification would be helpful.

**Comment by farshidtz** [comment]
`/things{?offset,limit,sort_by,sort_order}` is an optional API endpoint. If someone wants to query all TDs but as smaller subsets on a directory that doesn't implement pagination, they can use the JSONPath API and call `/search/jsonpath?query=$[start:end]` which is mandatory and always available. 

That's why we have this text before introducing the optional pagination:
> There may be scenarios in which clients need to retrieve the collection in small subsets of TDs. While the Search API (§ 6.2.2.4 Search) does offer the ability to query a specific range, it may not be optimal, nor developer-friendly.

In other words, the search API can be used for filtering/listing as well as for selection of fragments. 

But if I have to explain this here to convince you, there is definitely something wrong with the wording in the spec. Will make a PR to improve.

**Comment by mmccool** [comment]
PR merged, should address concerns, propose closing this issue.

**Comment by mmccool** [comment]
Resolution: assume this was dealt with by recent PRs.
