### ISSUE TITLE
Define role of "Discoverer/Registerer"

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#216]
For brownfield devices we probably need to define a "Discoverer" process/function  that generates the TD and registers it with a Directory service, or replies on the Things's behalf (for Direct discovery).   Latter is related to shadows/proxies.

To do: needs a better/less confusing name for this role...

_Originally posted by @mmccool in https://github.com/w3c/wot-discovery/issues/53#issuecomment-700663727_

**Comment by farshidtz** [comment]
I just got the chance to look at this new term added by #222 .

Why is it called Discoverer instead of [Registerer](https://www.merriam-webster.com/dictionary/registerer)? This entity doesn't do discovery, it does registration.

**Comment by benfrancis** [comment]
Some unsolicited feedback...

The entity which generates/produces a Thing Description for a (non-self-describing) device and the entity which registers that Thing Description with a directory may not always be the same. The former is likely to be a server (e.g. serving a Thing Description over HTTP) and the latter is likely to be a client (consuming the Directory Service API).

An entity which performs both functions is probably a "gateway" which is generating a Thing Description for a non-WoT device and exposing it via its own directory [1]. I can't otherwise imagine a Web Thing which would register itself with a directory. 

It may help to explain some concrete use cases you have in mind.

----
1.In this use case it's probably not always possible to expose all features of the Directory Service API (e.g. updating) to all clients, see #208.

**Comment by mmccool** [comment]
- is a distinction between the term and the definition.  Let's get the definition right first
- regarding ben's point, the "discoverer/registerer" would fetch the TD from the generator (the server in Ben's example) and then "register" it with the TDD (as a client).  So it's still a "registerer".  But maybe we also want to define a "generator" and note that the "registerer" may or may not be the "generator".  
- definition currently talks only about registration, not fetching.  If we have both, "discoverer" may be better (implies both actions, but then definition needs updating... it was my original intention to include both).

**Comment by benfrancis** [comment]
@mmccool wrote:
> regarding ben's point, the "discoverer/registerer" would fetch the TD from the generator (the server in Ben's example) and then "register" it with the TDD (as a client). So it's still a "registerer". But maybe we also want to define a "generator" and note that the "registerer" may or may not be the "generator".
> definition currently talks only about registration, not fetching. If we have both, "discoverer" may be better (implies both actions, but then definition needs updating... it was my original intention to include both).

Could the entity which sends HTTP requests to the HTTP server serving the Directory Service API simply be referred to as a "client"? Or perhaps a "Directory Consumer" since it "consumes" the Directory Service API?

An entity which produces a Thing Description is often referred to as a "Producer", though oddly I'm not sure that's formally defined anywhere in the way that "Consumer" is.

**Comment by mlagally** [comment]
Please don't forget if there are name or definition changes changes to provide updated terminology for architecture.

**Comment by mmccool** [comment]
- Current PR for vocab in Architecture has the term "Discoverer"
- However this definition is as follows, and says "generates": "An entity that generates and registers a TD with an exploration service on behalf of a Thing which may not be able to do it for itself."
- There are cases where a "discoverer" just fetches a TD provided elsewhere.  Also "generates" includes the case of instantiating a TM as a TD.
- It would be useful to have a "Registerer" agent as well defined and maybe a "Generator/Fetcher".
- Propose changing definition slightly to say "generates, fetches, or instantiates"
- After we get the definition correct, we can discuss the name.  Maybe "Generator"?  Also avoids the extra -er.
