### ISSUE TITLE
Influence of UPDATE or PATCH operation on version

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-discovery#255]
Given that a successful update or patch ideally changes the TD (a MUST for PATCH), shouldn't the `version` field in the TD change? I do not find any assertion or recommendation/guideline in the spec about this. There can be of course a lot of ways this can be done so I don't think that an assertion would be feasible. Some complications I could think of:
- `version` not present in the initial TD and in the updated TD
- `version` disappearing in the updated TD
- `version` appearing in the updated TD
- `version` decrementing
- validation of the `version` change, i.e. how big is the change and what mechanism is used

Other than the client proactively changing it, can the directory change it itself?

**Comment by farshidtz** [comment]
As per current spec, the directory only cares about the validity of the TD as well as `id` and `registration` fields. Other top level fields such as `created`, `updated`, `version` are not consumed or changed because they are associated with the TD instance beyond the scope of the directory. A TD instance may be created during onboarding and versioned arbitrarily (it is optional), before being registered inside the directory.

Use-case specific version processing can be added to a directory, in form of a [validation](https://w3c.github.io/wot-discovery/#validation), which is not fully defined right now. See https://github.com/w3c/wot-discovery/issues/99
