### ISSUE TITLE
Discovery document feedback

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-discovery#308]
I read through the document and would like to share some of my findings/comments.
Please take it with a grain of salt since I am not English native speaker 🙃.

## Typos

I created https://github.com/w3c/wot-discovery/pull/307 with some typo fixes.

## Wording

Section [5. Discoverer Process](https://w3c.github.io/wot-discovery/#discoverer-process) has a paragraph that talks about two components but somehow does not not *properly* mention  the 2nd part...

Maybe it can be rephrased?

It is permissible to split the implementation of a Discoverer into two components, one that fetches/reads a TD and sets up a configuration during installation to be used by a run-time component that cannot itself read TDs.
->
It is permissible to split the implementation of a Discoverer into two components, one that fetches/reads a TD and **??? TWO THAT ???** sets up a configuration during installation to be used by a run-time component that cannot itself read TDs.

## Singular vs. Plural

Section [5. Discoverer Process](https://w3c.github.io/wot-discovery/#discoverer-process) again.

If multiple invocations of a single Introduction mechanism is supported
If multiple invocations of a single Introduction mechanism **ARE** supported

## Duplicate error codes

In [7.2.2.1.2 Retrieval](https://w3c.github.io/wot-discovery/#exploration-directory-api-things-retrieval), [7.2.2.1.3 Update](https://w3c.github.io/wot-discovery/#exploration-directory-api-things-update) , and  [7.2.2.1.4 Deletion](https://w3c.github.io/wot-discovery/#exploration-directory-api-things-deletion) there are duplicate error codes.

I don't think this is desired. Moreover, most of them are not sorted like 404, 401, 403

![grafik](https://user-images.githubusercontent.com/11281461/168085157-aabe01a3-2800-43f6-95df-5da7bee0394f.png)

**Comment by mmccool** [comment]
Thanks Daniel for the review!

I'm prepping another PR that I hope will clean up Section 5.  Ben's review (Issue #299) mentions some of these points, esp in section 5.  We recently merged a [PR into Architecture](https://github.com/w3c/wot-architecture/pull/746) that updated the definition of "Discoverer" so that part of the general terminology cleanup needed is done at least.

Some of your other issues, e.g. about duplicate error codes, we probably want to have separate PRs for.  I expect I will have a PR that addresses at least some of these points on Monday, at which point we might want to break this issue and Ben's up into a set of smaller unrelated issues that we can have separate PRs addressing.

**Comment by mmccool** [comment]
Propose closing, as the document has changed enough by now that fresh reviews are needed.
