### ISSUE TITLE
Should we make SSE informative?

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#417]
See https://github.com/w3c/wot-discovery/issues/185#issuecomment-1258165394

Should we keep SSE (and the Event API) as normative, or make it informative?  Not clear we have sufficient implementation experience.  We do have two implementations, but they are both servers.  Unfortunately we don't have clients to test these with.

**Comment by mmccool** [comment]
Let's FORCE these assertions/section (Events API) as being as at-risk, so that we CAN take them out of the PR.

**Comment by relu91** [comment]
Just to clarify some points in https://github.com/w3c/wot-discovery/issues/185#issuecomment-1258165394:
> we currently don't have client implementations - in theory, node-wot and Node-RED could implement, however.

Node-wot has already a [client](https://github.com/eclipse/thingweb.node-wot/blob/d28218a7d183f4bf05fe9b54e4a3131be4f072c7/packages/binding-http/src/subscription-protocols.ts#L92) implementation (even the server side is implemented but I think it is not relevant)

> make events informative; current SSE implementations incomplete, and retention is a problem (needs custom impl).

This is not entirely true; unless I missed something, Zion implementation **should** be complete. However, I agree that retention has scalability issues. We implemented a "placeholder* strategy because we were worried about retaining all the events *forever*, probably we just need a best-effort approach (i.e. is not guaranteed that the TDD will give back all the events you missed). In my understanding, the [SSE Specification](https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events) does not oblige you to keep track of **all** the events that happened in the past.  

p.s. sorry for missing today's discussion.

**Comment by mmccool** [comment]
So the CR publication includes the SSE assertions; unfortunately, we did NOT force them to be marked as at-risk.  That means we are now committed to those assertions, and I propose closing this issue as "resolved".  However, while ok on a LAN, SSE is not great for cloud services, not being very scalable, so I'll create another issue to look at alternative event mechanisms in Discovery 2.0 (e.g. web hooks).
