### ISSUE TITLE
Define the WoT-Directory type somewhere (eg in new version of context, in 1.1)

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#43]
Could put in the v1.1 context file.  Should probably be just "Directory".

**Comment by relu91** [comment]
I think we should consider if in the feature TDD related terms will grow. Considering that we are also defining a data model for TD stored in directories (see issue https://github.com/w3c/wot-discovery/issues/98) we could define our context without filling the Thing Description context file with unrelated stuff.

**Comment by mmccool** [comment]
To recap discussion:
- We need to quickly determine during introduction whether a link points at a Thing or a Directory
- We *could* use a special context file for this, but I think an @type is more direct and clearer
- We could always define the Directory @type in a context file for directories, and use a prefix to avoid any possibility of name conflicts (e.g. dir:Directory).
- We need a context file anyway...

**Comment by farshidtz** [comment]
`DirectoryDescription` type has been added to a local discovery context: https://github.com/w3c/wot-discovery/blob/main/context/discovery-context.jsonld

**Comment by benfrancis** [comment]
From #133

> Why does a description of a thing have a `@type` of `Thing`, but a description of a directory has a `@type` of `DirectoryDescription`? Surely it should either be `ThingDescription` & `DirectoryDescription` or `Thing` & `Directory` for consistency?

**Comment by farshidtz** [comment]
It seems that the TD 1.0 spec uses `@type` to refer to the actual entities, rather than the description of it. For example:
- `Thing` 
- `saref:LightSwitch`
- `saref:TemperatureSensor`

Following that, it makes sense to also use `Directory` type (instead of `DirectoryDescription`). 

I think there were two reasons for choosing `DirectoryDescription` (@AndreaCimminoArriaga please correct me if i'm wrong):

1. We wanted to reserve `Directory` for referring to the directory itself in the ontology. I now think it is okay to reuse the actual thing's type as TD type since it is a common practice. But we should check the spec and ontology to make sure this change doesn't add confusion.
2. We wanted to make it consistent with `LinkDescription`. As mentioned in https://github.com/w3c/wot-discovery/issues/34#issuecomment-740009713, we can't use `Link`, since TD already uses that.

But there is a new addition in TD 1.1:
- `ThingModel` which can be combined with other types. This one makes less sense to me: it is not a model of an actual entity. "A Thing Model is a template for Thing Descriptions". Previously called: Thing Description Template.

If `Thing` refers to Thing Description, then the discovery types could be `ThingDirectory` and `ThingLink`!

Maybe @sebastiankb, @vcharpenay, @egekorkan, or @mmccool could clarify.

**Comment by AndreaCimminoArriaga** [comment]
Correct @farshidtz. One of the reasons was also because we were mixing pagination information with TDs so we had to distinguish what a Directory was (that had such pagination information), and what Directory Descriptions were (stored `Thing` referring to directories). Nevertheless, now that the pagination is not mixing information I think we could evolve the types names. I like the idea of changing the names to `ThingDirectory` and `ThingLink`.

**Comment by farshidtz** [comment]
The type has been changed to `ThingDirectory`, in the discovery context: https://github.com/w3c/wot-discovery/blob/main/context/discovery-context.jsonld
