### ISSUE TITLE
Define error responses

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#44]
For error response, having an array so we can define error responses would be quite useful.  Use case supporting https://github.com/w3c/wot-thing-description/issues/617

**Comment by farshidtz** [comment]
Not just errors, but also for various success responses with corresponding status codes, content types, and headers. 

E.g. for PUTing TD:
```json
{
    "href": "/td/{id}",
    "htv:methodName": "PUT",
    "contentType": "application/td+json",
    "response": [
        {
            "description": "Created new resource",
            "htv:statusCodeValue": 201
        },
        {
            "description": "Updated existing resource",
            "htv:statusCodeValue": 204
        },
        {
            "description": "Invalid input",
            "htv:statusCodeValue": 400,
            "contentType": "application/json"
        },
        {
            "description": "No authentication",
            "htv:statusCodeValue": 401,
            "contentType": "application/json"
        },
        {
            "description": "Insufficient rights",
            "htv:statusCodeValue": 403,
            "contentType": "application/json"
        }
    ]
}
```

More [examples](https://github.com/w3c/wot-thing-description/issues/617#issuecomment-665105127) are provided as comments.

**Comment by egekorkan** [comment]
Also related to https://github.com/w3c/wot-scripting-api/issues/200

I think that the whole working group needs to define error types that are WoT-specific but at the same time mappeable to protocol errors/status codes.

**Comment by benfrancis** [comment]
I definitely agree this is needed and in the case of the directory API these error conditions can be documented in the API specification so that clients know what the different errors mean.

If this syntax was generalised to all Thing Descriptions I'm not sure how clients would automatically assign meaning to arbitrary response codes and human-readable descriptions and distinguish between success and error conditions in different protocols. As @egekorkan says it may be necessary to define WoT-specific error codes which can then be mapped onto different underlying protocols.

**Comment by farshidtz** [comment]
Discussed in https://github.com/w3c/wot-thing-description/issues/617 and added to [TD 1.1](https://github.com/w3c/wot-thing-description/pull/1042).
