### ISSUE TITLE
Clarifying Introduction Mechanisms

### ISSUE THREAD

**Issue by k-toumura** [w3c/wot-discovery#53]
To clarify introduction mechanisms, I wrote a diagram of discovery flow.

![discovery-lifecycle](https://user-images.githubusercontent.com/30313213/90398882-0c76f580-e0d5-11ea-81d6-3538c710abf5.png)

- Are there any other mechanisms we should add?
- Basically, introduction mechanism resolves to the URL of Thing Description of Thing or Directory.   Should we include a mechanism that resolves directly to the Thing Description (e.g. DID resolves to a DID document, which may contain a TD)?

**Comment by farshidtz** [comment]
Related to DNS-SD for service type and TXT record definition:
- https://github.com/w3c/wot-discovery/issues/5
- https://github.com/w3c/wot-testing/issues/34
- [Fujitsu use case](https://github.com/w3c/wot-discovery/tree/master/prior-work/fujitsu)

**Comment by k-toumura** [comment]
Use of [RFC8615 Well-Known Uniform Resource Identifiers (URIs)](https://tools.ietf.org/html/rfc8615)
- TD self-hosting on well-known URI, such as `/.well-known/wot-thing-description`
- similar to CoRE devices ([RFC6690 Constrained RESTful Environments (CoRE) Link Format](https://tools.ietf.org/html/rfc6690))

**Comment by benfrancis** [comment]
See [mDNS/DNS-SD discovery mechanism](https://iot.mozilla.org/wot/#mdns-dns-sd) used by Mozilla's WebThings Gateway and WebThings Framework libraries. Discussion on naming choices [here](https://github.com/mozilla-iot/gateway/issues/696).

**Comment by danielpeintner** [comment]
>     * TD self-hosting on well-known URI, such as `/.well-known/wot-thing-description`

Just for your information: In node-wot we decided to report the TD when retrieving the thing URL itself.
Having said that, I am fine with reporting  the TD under any well known URI ... it just needs to be pre-scribed *what* the URI should be for a given protocol

**Comment by k-toumura** [comment]
Revise the diagram based on above discussion:
![discovery-lifecycle](https://user-images.githubusercontent.com/30313213/93015860-d3f50980-f5f7-11ea-81aa-a271d3fad7cf.png)

**Comment by mmccool** [comment]
I like that diagram, and it should definitely go into the introductory "architecture" section.  One thing I'm struggling with is how to cleanly separate "Introduction" and "Exploration" in the case of peer-to-peer discovery.   I think they need to at least be *conceptually* separate and the architecture needs to satisfy the other goals of privacy protection, etc.

**Comment by mmccool** [comment]
@danielpeintner In my devices I've been returning just the "title" when accessing the base URL of a device, but returning the TD is fine, too.  In practice, it is also possible to return the TD from multiple URLs on a device (eg both .well-known and the base), although I'd prefer not to do that.  Probably we should talk with the CoRE people.  In any case, however, the TD needs to be appropriately protected with authentication, etc.  In fact ANY metadata should be protected via authentication, and that includes just the title (eg what I have been doing with the base URL should technically require authentication).  One issue though is WHAT kind of authentication a device requires to access its metadata.  We could declare that in the TD, but you won't be able to access the TD until you know it so it's pointless.  So we have to limit it to mechanisms that also state the required authentication in the protocol (fortunately, all the ones I know of do: Bearer, Basic, and Digest), but we also need to require a secure protocol (http/TLS (https), which is however a pain to set up in a local network... so maybe coaps/DTLS (coaps) would be better...).

Anyway, @k-toumura created a PR to add this figure to the current document, and I merged it, , and so probably should close this issue and after creating additional, more specific issues to deal with well-known URLs, required authentication and encryption methods for retrieval of metadata when using peer-to-peer discovery, and so forth.   In general it's not just "Introductions" that need clarifying, it's the overall architecture and in particular how to deal with peer-to-peer discovery (I think directories are easier since we can be more prescriptive.  My general feeling is that we should be prescriptive for peer-to-peer discovery too, since it only applies to "new" devices, brownfield devices will not be providing their own TDs so we don't have to worry about being "descriptive" but can SAY what devices MUST do to support peer-to-peer discovery).

**Comment by mmccool** [comment]
A final thought: for brownfield devices we probably need to define a "Discoverer" process/function (eg in the Architecture document) that generates the TD and registers it with a Directory service.   Note that I am thinking in terms of "functional" architecture, in an actual implementation the "Discoverer" and the "Directory" could be implemented in the same service (although if it was me I'd break them up into loosely-coupled services since you'll need different "Discoverers" for different ecosystems, each with their own software stack, and trying to integrate multiple software stacks into a single process is not that easy - imagine if they are in different languages, for instance).

**Comment by mmccool** [comment]
Resolution: We have now solved the general problem and need to create and follow up on smaller clean-up issues.  So we can close this and create more focused issues as needed (e.g. to deal with the Discoverer issue, which I will create).
