### ISSUE TITLE
Define a concrete network API for a TD Directory service

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-discovery#8]
- Suitable for deployment as a service
- Implementable as a containerized service that can be integrated with stacks like EdgeX (but should not be specific to any particular stack)
- Support secured access, specifically OAuth2
- Integrate with Conexxus/EdgeX PoC
- Support partial TD template matching
- Support WoT Scripting discovery

**Comment by mmccool** [comment]
Should see if there is an existing implementation we can update and use.  @vcharpenay - what is the status of your TD Directory implementation?

**Comment by vcharpenay** [comment]
my implementation is not fully supporting the latest TD version because there is no up-to-date implementation of JSON-LD 1.1 that can correctly process TD documents. However, the JSON-LD 1.1 syntax [has become a PR in March](https://www.w3.org/TR/json-ld11/https://www.w3.org/TR/json-ld11/). Implementations may follow soon.

**Comment by mmccool** [comment]
done
